<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>
<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>
]>
<!-- Begin document body -->
<MEME version="5.0.5" release="Mon Mar 18 20:12:19 2019 -0700">
<alphabet name="Protein" like="protein">
<letter id="A" symbol="A" name="Alanine" colour="0000CC"/>
</alphabet>
<sequence id="sequence_0" name="chr21_19617074_19617124_+" length="50" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.294</value>
</letter_frequencies>
</training_set>
<model>
<scores>
<alphabet_matrix>
<value letter_id="A">-32</value>
<value letter_id="A">-79</value>
<value letter_id="A">11</value>
<value letter_id="A">-596</value>
<value letter_id="A">165</value>
<value letter_id="A">-838</value>
<value letter_id="A">176</value>
<value letter_id="A">134</value>
<value letter_id="A">165</value>
<value letter_id="A">147</value>
<value letter_id="A">0.240000</value>
<value letter_id="A">0.280000</value>
<value letter_id="A">0.160000</value>
<value letter_id="A">0.320000</value>
<value letter_id="A">0.000000</value>
<value letter_id="A">0.960000</value>
<value letter_id="A">0.000000</value>
<value letter_id="A">1.000000</value>
<value letter_id="A">0.760000</value>
<value letter_id="A">0.960000</value>
<value letter_id="A">0.840000</value>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GA][GA][GC][GA]TATA[AT]AA
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_24" position="12" strand="none" pvalue="1.06e-06" >
<left_flank>AAGGCCAGGA</left_flank>
<site>
<letter_ref letter_id="G"/>
</site>
<right_flank>GCCTGAGAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_25" position="36" strand="none" pvalue="3.41e-06" >
<left_flank>ACAGGCCCTG</left_flank>
<right_flank>GCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_19" position="9" strand="none" pvalue="3.41e-06" >
<left_flank>CAGGCCCTG</left_flank>
<right_flank>GCCCCAGCAG</right_flank>
<scanned_sites sequence_id="sequence_4" pvalue="1.22e-03" num_sites="1"><scanned_site motif_id="motif_1" strand="none" position="12" pvalue="3.06e-05"/>
<scanned_sites sequence_id="sequence_5" pvalue="1.53e-03" num_sites="1"><scanned_site motif_id="motif_1" strand="none" position="0" pvalue="3.82e-05"/>
<scanned_sites sequence_id="sequence_6" pvalue="6.70e-04" num_sites="1"><scanned_site motif_id="motif_1" strand="none" position="15" pvalue="1.68e-05"/>
</MEME>
